// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpbpeyflnpoiivxnadyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwYnBleWZsbnBvaWl2eG5hZHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDEyNTEsImV4cCI6MjA2MTExNzI1MX0.752qK_c_JFjIvORqgpLvxv1malJWQhuQ0WjzJJpAux4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);